version: '3.8'

services:
  ai3d_nginx:
    build: ./nginx
    image: nginx:alpine
    restart: unless-stopped
    container_name: ai3d_nginx
    ports:
      - "81:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro"
      - "./nginx/static:/static:ro"
    depends_on:
      - ai3d_app
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  ai3d_db:
    image: postgres:15-alpine
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - "5432:5432"
    container_name: ai3d_db
    volumes:
      - ai3d-postgres-data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    env_file:
      - .env

  ai3d_app:
    build: .
    image: ai3d:1.0.0
    container_name: ai3d_app
    restart: unless-stopped
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./nginx:/opt/nginx:rw"
    env_file:
      - ./.docker.env
    expose:
      - "8000"
    depends_on:
      - ai3d_db
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  ai3d-postgres-data:
    driver: local
