"""add user role

Revision ID: 278a3ec785cb
Revises: f86fed18df35
Create Date: 2024-01-08 19:12:14.042835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "278a3ec785cb"
down_revision = "f86fed18df35"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("role", sa.String(), server_default="user", nullable=True)
    )
    op.execute("UPDATE \"user\" SET role = 'user' WHERE role IS NULL;")
    op.alter_column(
        "user",
        "role",
        existing_type=sa.VARCHAR(),
        nullable=False,
        server_default="user",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role")
    # ### end Alembic commands ###
